version: "3"

tasks:
  plan:
    desc: Proxmox インフラ差分を確認 (terraform plan)
    cmds:
      - terraform plan {{.CLI_ARGS}}

  apply:
    desc: Proxmox インフラを適用 (terraform apply)
    cmds:
      - terraform apply {{.CLI_ARGS}}
